import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import fetcher from "@/utils/fetcher";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const fileUpload = (e: any) => {
    console.log(e.target.files[0]);
    if (e.target.files[0]) {
      const file: File = e.target.files[0];
      const stream = file.stream();
      const filename = file.name;
      console.log("filename", filename, stream);
      const { signal } = new AbortController();

      fetcher("http://localhost:3001/api/files/fileStreamUpload", {
        method: "POST",
        // headers: {
        //   Accept: "application/json",
        //   "Content-Type": "application/octet-stream",
        // },
        signal,
        body: stream,
        duplex: "half",
      }).then((res) => console.log("======", res));
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input type="file" onChange={fileUpload} />
      </main>
    </>
  );
}
